Fix #63 and change #54 to use an early return
RanvierMUD/core pull request #121
Opened 2020-06-06 21:26 UTC by azigler

- Properly define `Room.exits` for documentation purposes.
- Use early return on `Character.unfollow()`

2020-06-08 00:19 UTC, seanohue commented on src/Character.js
> -    if (!this.inventory.size) {
getting rid of the null inventor is a blessing

2020-06-30 03:54 UTC, nelsonsbrian requested changes
Can't we get rid of a few more things with this inventory fix?

Like equip() Remove the 'if this.inventory' check? line 365
Cant we just use _setupInventory in the constructor and pass in the inventory with the data? Then we can get rid of all the extra _setupInventory calls in Character.js

Can do the same in Item.js, have a single setupInventory and not have to have checks in all the other places.

2020-07-09 04:32 UTC, azigler commented
@nelsonsbrian I totally agree, so I just added those changes for `Item.js` and `Character.js` to the PR.

2020-07-11 20:47 UTC, azigler commented
I rolled back those `Inventory` setup changes because they caused inventories to not be properly initialized (my containers were empty).

2022-11-08 19:14 UTC, closed without merging